### ISSUE TITLE
Reach out

### ISSUE THREAD

**Issue by shaoyijia** [rmcc3/experiments-progressive-growing#1]
Hi, thank you so much for your contribution to our [STORM repo](https://github.com/stanford-oval/storm). We have some major improvement work-in-progress. I am wondering if you are willing to have more discussion on how we could better leverage contribution.

Sorry for leaving an issue here - I cannot find your contact info on your GitHub account. If you would like to have the discussion, you could drop me [an email](mailto:shaoyj@stanford.edu). I will quickly follow up with more information. Many thanks again!

**Comment by BadAtCaptchas** [comment]
Email sent.
