### ISSUE TITLE
[Discussion/Question] Have you abandoned the experiment?

### ISSUE THREAD

**Issue by Targren** [rmcc3/experiments-progressive-growing#2]
I just wanted to reach out to see if you were still intending to refine and develop this? I'm afraid of the answer since the reddit thread and comments got pulled down the same day, but if you remember me from the thread, I was a huge fan of what I was able to do with playing with it that day. 

If not, I'll keep the old install with the manual patch around and make do with that, and thank you for that, but if you reach the point where you have something like a polished extension which works with other extensions, that would be amazing. 

Either way, thanks. :)

**Comment by BadAtCaptchas** [comment]
> I just wanted to reach out to see if you were still intending to refine and develop this? I'm afraid of the answer since the reddit thread and comments got pulled down the same day, but if you remember me from the thread, I was a huge fan of what I was able to do with playing with it that day.
> 
> If not, I'll keep the old install with the manual patch around and make do with that, and thank you for that, but if you reach the point where you have something like a polished extension which works with other extensions, that would be amazing.
> 
> Either way, thanks. :)

I didn't do more since auto was making a big update which would have resulted in a loss of further progress, I did not forget about the project though. I would like to have this as an extension rather than editing core files.

**Comment by Targren** [comment]
Awesome. Yeah, it was the big update that prompted me to ask. I was just more worried because the thread was nuked (but I can understand not wanting to argue with the twonks on reddit <_<) 

Looking forward to the future work, then. Thanks!
